language: cpp
os:
  - osx
env:
  global:
    - secure: xyVcJwKgu8WFJzCtxOs6Vy3E093Ea+OFCHodFZtNm9EBVcivZj2w4dglQ0gvQYsKjy06DgjCfyz9rIP2n/juaVlj89HvLALJX0/oIM820ePkqDzl54I/7Bk/YA2ROOKFrd8DhZzofQXRSNXIIuR5qGDBgq1H4UEAtSmcogiwGoOIHdQg6KYvyXw2jleZrvNeNErbr10BOgMikyiTxtqGsW5Wh5hVYScneN3u3K0uSvXGQeMysf/uvWOYHXzgngdfhJTTx0htHyTMsO/0VAfQPLJgKvlj0mGc4I0emPFjp+EkFKvRJffLxLMwK4hpej20yrqoWfJajZftZg9zoVPLzyX0tL78SjAhHAyLA8iYlxh1d9KXHVSjByJsVe1vwcMpyQ7+NYvqUSYUHOhpmohz8eohtS74xC7AquEnAyXRNG8WEEXG+N1yxIyaRFSIh56xvtenwp8okUndl5kFnfjzLZrUywnWqH7idxSpaRKmgW8opddv77JqX7pBayJHcEBze0VuIb7pOqa+kRuzl6m+u1IuBDODuRcQcAGUP5s1zP9Kcyj/HtQF853wH539kibp+gbFRLMpwVqCOlVxyOjOfC56HDx61smabQCFmm07JmXFZjBi/5iMlz1YZv2CkRL6X0/tkxaY4oQpJKuS1zV7gWyptn/qurKz+wtygY7FxW0=
    - secure: eGYgb6xoFlfi6q0BjcS0AX29g+in4kzzUmuXm+fBgyvjOYH2muFi/07AM7sq/2zpH919YV8bc8DmznqPJ9SvX1HjqWSZT5JrTWXQ2NS8tVrJ+bK6YjXK7Ngg37TzEcO0DroOYr3jvQ7FCN1tvEeEYLDlcGnYtl3lUdv74xD7G97VfPd1tuXnb6NXqSCjf69smVKCQOATwq3vCi3+O6mYvGA0sHdalX4nOstVZV+KcaRcWL5cszHbdNBFOaRzNoLQSWYiDLXqYg3WsOEMwLE3pNS03Pkuuo6pKTwUVPYW0cijvxMjrNcqin0HgSLAN0/d4QnZdgyQsf/EWWj913quB95vJV9SKefdJV+UJ2i++BIImF6aNqhzeY2ftIfq9K+7foDuzVg8uODJGKz+OJZQo05nlQEOoqGgL8gZkJNGzKc1Vpwp0GjyC1gRrdiuE3ay4Aqq4jZlmk2zjHoi0PXGF1diYVuUDWTSZr61N4F2QZuBMV+NsJVEso2EFlR2FirMrSbp93vGkrKuzmLtCUkihsCyv8KWUEvT9VFwJaPpyux1MkHnu4BHq06ICjh/u+esRWarhikuZslw+nQMy0DomkGnz+Sb2IuHPymvjjxW8M26fdVi0gROdVg7HOsTU0kvwbdCrLBWQ93zn0uCqU2NnwSjeyHv3HUcyj3+8SUpES4=
branches:
  only:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_script:
  - bash script/install_cert.sh
script:
  - git submodule update --init --recursive
  - nvm install $(cat .node-version)
  - nvm use $(cat .node-version)
  - npm install
  - npm run clean
  - npm run package-macos
  - mv ./release-builds/nkcv.dmg ./release-builds/nkcv-${TRAVIS_TAG}-macos.dmg
after_script:
  - bash script/uninstall_cert.sh
deploy:
  provider: releases
  api_key:
    secure: MOibK2+jhFIxKdWztYOyG/SCmXR8qprR7LaSOXsoyYSrGRGP0w8+Z+KxHZRttLWbWZ5dBdlePBFqeE8Ubpmvl4axQBNav1VxJA+GpKF5QEXWLFZUCeS/x6/cqW1bmYVtZ0WEnHsTAaBpAOkWitDOiUjUMoOLVZLyQUl7JMWyNoX61tJmB3LGih8HdPe5gR1y1BzKoBypyvAEtPXPQ8RJJ/uNwEhS7Mi7j97eXd/Z/K/Bu9Zpb9JW08mLarp9oGrAUWxrEig/JjuDX3rzJkyMPXWpQc+bjUuci7aeTEXY5wYPa2W7nUKVu4VhcFVYNvpGRNDlZIB/DC5xdku7lke3LUpN7rVtQicf882JuAv3vkRTy8evu0w+IDfzI8PirQIzrhrKZhgY3TSl1Kn1zYctnrWzJwJGjHG8GeP1eJsvG2xaocmHR6ezBVcFs7mDm+OYisSeCI1tv35zBNmmy8TsTWJnXJsg3ec1Q4I2uD7P3pxU6Xz/mINCyqPZKxNfr5+WpS7oadRVJQ+Z/t8CWaluBTyHbNbqMCf38ndtaDrBYpu/D+aQB57CT+FdqsjvsUPEX2m0H7jblF4J8M3AiReXgh0iiOH2W30bqmdr6TwlssdTkE7UEi6+RIFjYTJAGiYkG5JdKYcxu6CjfQEJ0kjw21FPgGTE7Nth2Z8EpQi30VA=
  file_glob: true
  file: ./release-builds/nkcv-*.dmg
  overwrite: true
  skip_cleanup: true
  prerelease: true
  on:
    tags: true
