language: cpp
os:
  - osx
before_install:
  - git submodule sync --recursive
  - git submodule update --init --recursive
script:
  - git clone https://github.com/riywo/ndenv ~/.ndenv
  - export PATH="$HOME/.ndenv/bin:$PATH"
  - eval "$(ndenv init -)"
  - ndenv install $(cat .node-version)
  - npm install
  - npm run package-macos
  - ls -la ./release-builds/nkcv-darwin-x64
