language: cpp
os:
  - osx
before_install:
  - git submodule sync --recursive
  - git submodule update --init --recursive
script:
  - nvm install $(cat .node-version)
  - nvm use $(cat .node-version)
  - which node
  - node --version
  - which npm
  - npm --version
  - npm install
  - npm run package-macos
  - ls -la ./release-builds
  - ls -la ./release-builds/nkcv-darwin-x64
